description: >
  Complete CI/CD workflow example for Maven-based projects using GitFlow branching strategy.
  This example demonstrates how to use the qqq-orb for automated building, testing, and releasing.

usage:
  version: 2.1
  orbs:
    qqq-orb: kingsrook/qqq-orb@0.3.0

  workflows:
    # Test workflow for feature branches
    test_only:
      jobs:
        - qqq-orb/mvn_test_only:
            context: [ qqq-maven-registry-credentials ]
      filters:
        branches:
          ignore: [develop, main, /release\/.*/, /hotfix\/.*/]

    # Snapshot deployment for develop branch
    publish_snapshot:
      jobs:
        - qqq-orb/mvn_publish:
            context: [ qqq-maven-registry-credentials ]
            branch_type: snapshot
      filters:
        branches:
          only: [develop]

    # Release candidate workflow
    publish_release_candidate:
      jobs:
        - qqq-orb/mvn_publish:
            context: [ qqq-maven-registry-credentials ]
            branch_type: release_candidate
      filters:
        branches:
          only: [/release\/.*/]

    # Production release workflow
    publish_release:
      jobs:
        - qqq-orb/mvn_publish:
            context: [ qqq-maven-registry-credentials ]
            branch_type: release
      filters:
        branches:
          only: [main]

    # Hotfix release workflow
    publish_hotfix_release:
      jobs:
        - qqq-orb/mvn_publish:
            context: [ qqq-maven-registry-credentials ]
            branch_type: hotfix
      filters:
        branches:
          only: [/hotfix\/.*/]
