description: >
  Complete CI/CD workflow example for Maven-based projects using GitFlow branching strategy.
  This example demonstrates how to use the qqq-orb for automated building, testing, and releasing.

usage:
  version: 2.1
  orbs:
    qqq-orb: kingsrook/qqq-orb@2.1

  workflows:
    # Test workflow for feature branches
    test_only:
      jobs:
        - qqq-orb/build:
            context: [ qqq-maven-registry-credentials ]
        - qqq-orb/test:
            context: [ qqq-maven-registry-credentials ]
            requires:
              - qqq-orb/build
      filters:
        branches:
          ignore: [develop, main, /release\/.*/, /hotfix\/.*/]

    # Snapshot deployment for develop branch
    publish_snapshot:
      jobs:
        - qqq-orb/publish_snapshot:
            context: [ qqq-maven-registry-credentials ]
      filters:
        branches:
          only: [develop]

    # Release candidate workflow
    publish_release_candidate:
      jobs:
        - qqq-orb/publish_release_candidate:
            context: [ qqq-maven-registry-credentials ]
      filters:
        branches:
          only: [/release\/.*/]

    # Production release workflow
    publish_release:
      jobs:
        - qqq-orb/publish_release:
            context: [ qqq-maven-registry-credentials ]
      filters:
        branches:
          only: [main]

    # Hotfix release workflow
    publish_hotfix_release::
      jobs:
        - qqq-orb/publish_hotfix_release:
            context: [ qqq-maven-registry-credentials ]
      filters:
        branches:
          only: [/hotfix\/.*/]
